[workspace]
resolver = "3"
members = ["libnet_bindings", "libnet"]

[profile.release]
lto = "thin"

[profile.bench]
debug = true

[workspace.dependencies]
ahash = "0.8.12"
android_logger = "0.15.1"
base64 = "0.22.1"
bincode = "2.0.1"
criterion = { version = "0.8.2", features = ["html_reports"] }
etherparse = "0.20.1"
getrandom = "0.4.2"
log = "0.4.29"
lru = "0.16.3"
mio = { version="1.2.0", features=["net","os-poll","os-ext"] }
memmap2 = "0.9.10"
quiche = "0.28.0"
simple-dns = "0.11.3"
simple_logger = "5.2.0"
thiserror = "2.0.18"
uniffi = { version = "0.31.1", features = ["cli"] }
url = "2.5.8"
