[package]
name = "net"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "net"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
base64 = "0.22.1"
etherparse = "0.19.0"
getrandom = "0.3.4"
libc = "0.2.177"
log = "0.4.28"
mio = { version="1.1.0", features=["net","os-poll","os-ext"] }
quiche = "0.24.6"
simple-dns = "0.11.0"
thiserror = "2.0.17"
uniffi = { version = "0.30.0", features = ["cli"] }
url = "2.5.7"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15.1"

[profile.release]
lto = "fat"
