[package]
name = "net"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "net"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
base64 = "0.22.1"
etherparse = "0.17.0"
getrandom = "0.3.2"
libc = "0.2.172"
log = "0.4.27"
mio = { version="1.0.3", features=["net","os-poll","os-ext"] }
quiche = "0.23.7"
simple-dns = "0.10.1"
thiserror = "2.0.12"
uniffi = { version = "0.29.1", features = ["cli"] }
url = "2.5.4"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14.1"

[profile.release]
lto = "fat"
