name: DNSNet Test

on:
  pull_request:
    paths-ignore:
      - '**/baseline-prof.txt'
      - '**/startup-prof.txt'
      - '**/.github/**'
  push:
    branches:
      - a-couple-updates
    paths-ignore:
      - '**/baseline-prof.txt'
      - '**/startup-prof.txt'
      - '**/.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29
          link-to-sdk: true

      - name: Run tests
        run: |
          ./gradlew :service:test --stacktrace
          cd service && cargo test
